---

- name: "Main | Ensure pasteque jsadmin directory exists"
  file:
    path: "{{ pasteque_jsadmin_dir }}"
    state: directory
    owner: root
    group: www-data
    mode: 0775
  become: true
  register: _reg_pasteque_jsadmin_dir
  notify: _handler_update_files_ownership

- name: "Main | Clone or Update the repo"
  git:
    repo: "{{ pasteque_jsadmin_git_repo }}"
    version: "{{ pasteque_jsadmin_git_version }}"
    dest: "{{ pasteque_jsadmin_dir }}"
    clone: true
    update: true
    accept_hostkey: true
  register: _reg_pasteque_jsadmin_repo
  become: false
  notify: _handler_update_files_ownership

- name: "Main | Ensure file permissions aren't checked"
  git_config:
    name: core.fileMode
    scope: local
    repo: "{{ pasteque_jsadmin_dir }}"
    value: "false"
