---
# handlers file for ansible-role-pasteque-jsadmin

- name: _handler_update_files_ownership
  file:
    path: "{{ pasteque_jsadmin_dir }}"
    state: directory
    recurse: yes
    owner: root
    group: www-data
  become: yes
